import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  readonly children: React.ReactNode,
  params: {
    lng: string
  }
};

export default function RootLayout({ children, params: { lng } }: RootLayoutProps) {

  return (
    <html lang={lng}>
      <body>{children}</body>
    </html>
  );
}
